### ISSUE TITLE
My first Project

### ISSUE THREAD

**Issue by Jmayorgagx13** [duo-labs/webauthn#125]
Hell fixing API Bug

**Comment by MasterKale** [comment]
@Jmayorgagx13 are you having trouble navigating GitHub? This is definitely not the correct forum for that. Please keep issues in this repo on the topic of this library and its functionality.

If the issues you've created on here _are_ related to this project, please try creating a new issue with details of what the problem you're having with this library, including sample code so that we can understand the nature of your problem and propose solutions.
