### ISSUE TITLE
CollectedClientData.Verify does not match spec

### ISSUE THREAD

**Issue by e3b0c442** [duo-labs/webauthn#59]
Hello,

I'm currently working on using this library to migrate Gitea's FIDO U2F implementation to standard WebAuthn. While doing so, I came across an error: `Error validating origin`.

Digging deeper, I discovered in the `Verify(storedChallenge string, ceremony CeremonyType, relyingPartyOrigin string) error` method on `*CollectedClientData` that the validation does not appear to be matching the spec. [These lines](https://github.com/duo-labs/webauthn/blob/4bf9a0f776d4771afd9fc24e430ff667a087d3d1/protocol/client.go#L88-L92) verify the origin as described in Assertion step 9, however, they are not actually comparing the origins. By calling `clientDataOrigin.Hostname()`, the comparison ends up being `mydomain.com` vs `https://mydomain.com`; that is to say, `clientDataOrigin.Hostname()` is the same as the Relying Party ID, not the Relying Party Origin.

This may not be caught due to the fact that [on initialization, if `RPOrigin` is not provided in the config struct, RPOrigin is set to RPID](https://github.com/duo-labs/webauthn/blob/4bf9a0f776d4771afd9fc24e430ff667a087d3d1/webauthn/main.go#L51).

Happy to submit a PR if desired, but I potentially see this breaking implementations that are already using this library.

**Comment by nicksteele** [comment]
Hi @e3b0c442, happy new year and thanks for submitting this issue. Step 9 has been tricky due to inconsistencies browser/authenticator responses in the past, although I’d expect them to be more normalized now. Additionally, we should be assuming that `https` is in place, which is a general assertion of the WebAuthn spec. 

If you could submit a PR that would be excellent, and if it breaks current builds I’ll be wary of giving people a heads up of that and how to remediate the issue in the README. This library should be handling things as true to the specification as possible though.

**Comment by arianvp** [comment]
> Additionally, we should be assuming that https is in place, which is a general assertion of the WebAuthn spec.

Not fully true. It assumes a "secure context", which at least Firefox allows access to the webauthn API from  `localhost` over `http`.  But that seems like something that might be removed form the spec in the future https://www.w3.org/TR/secure-contexts/#localhost

(Also; happy new year!)
