### ISSUE TITLE
Using Protonmail's GopenPGP webauthn build fails in webauthncose

### ISSUE THREAD

**Issue by hg-runs** [duo-labs/webauthn#62]
I am playing around with protonmail's GopenPGP V2
https://github.com/ProtonMail/gopenpgp

Being forced to add
`replace golang.org/x/crypto => github.com/ProtonMail/crypto v0.0.0-20191122234321-e77a1f03baa0`
to go.mod the build suddenly fails while compiling webauthncose:
```
# github.com/duo-labs/webauthn/protocol/webauthncose
P:\go\dev\pkg\mod\github.com\duo-labs\webauthn@v0.0.0-20200102191737-d63dbd17cdd4\protocol\webauthncose\webauthncose.go:298:39: cannot use oKey (type "golang.org/x/crypto/ed25519".PublicKey) as type "crypto/ed25519".PublicKey in argument to marshalEd25519PublicKey
```

Obviously being unexperienced any hint or RTFM is appreciated!

**Comment by nicksteele** [comment]
it seems like the crypto library is incompatible with some of the dependencies that `webauthncose` relies on from the `crypto` library. You may need to update some of the methods that rely on certain `x/crypto`-specific methods so that it can be compatible with the `ProtonMail/crypto` library. Sorry for the delayed response!
